-- AUTO-GENERATED by tools/voice/build-lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report
-- how long a sound file is; without them the Play button never resets itself.
--
-- Globals rather than a private namespace: a data addon cannot reach into
-- ZoneLore's, which is how AI_VoiceOverData_Vanilla does the same job.

local ADDON_NAME = ...

local pack = {
	version = 1,
	zones = {
	},
	subzones = {
	},
}

-- C_AddOns is the modern home of GetAddOnMetadata and the global is the older
-- one. A pack that reads only through C_AddOns errors at load on any client
-- that predates it, and a shipped pack cannot be fixed retroactively.
local GetAddOnMeta = (C_AddOns and C_AddOns.GetAddOnMetadata) or GetAddOnMetadata

-- The folder name comes from the loader rather than being baked in, so one
-- generated file serves every quality tier: ZoneLoreAudio and ZoneLoreAudio64
-- ship the same Sounds.lua and differ only in their .toc and their mp3s.
pack.addon = ADDON_NAME
pack.quality = GetAddOnMeta(ADDON_NAME, "X-ZoneLore-Quality") or "standard"
pack.bitrate = tonumber(GetAddOnMeta(ADDON_NAME, "X-ZoneLore-Bitrate")) or 0
pack.packVersion = GetAddOnMeta(ADDON_NAME, "Version") or "dev"

-- Defaulted rather than required: the two packs published before languages
-- existed carry no such key, and they are English.
pack.language = GetAddOnMeta(ADDON_NAME, "X-ZoneLore-Language") or "enUS"

-- Keyed by folder name so two tiers installed at once both register instead of
-- the second silently overwriting the first. Spoken Zones picks between them.
SpokenZonesAudioPacks = SpokenZonesAudioPacks or {}
SpokenZonesAudioPacks[ADDON_NAME] = pack

-- The registry under its former name, written with the same key so the two are one
-- pack to any reader. It keeps this zip working under ZoneLore 0.3 and later.
ZoneLoreAudioPacks = ZoneLoreAudioPacks or {}
ZoneLoreAudioPacks[ADDON_NAME] = pack

-- What ZoneLore 0.2 and earlier read. Harmless once the registries above exist,
-- and it keeps an old addon working with a new pack rather than going quiet.
ZoneLoreAudioData = ZoneLoreAudioData or pack
