-- AUTO-GENERATED by tools/voice/build-lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report
-- how long a sound file is; without them the Play button never resets itself.
--
-- A global rather than a private namespace: a data addon cannot reach into
-- ZoneLore's, which is how AI_VoiceOverData_Vanilla does the same job.

ZoneLoreAudioData = {
	version = 1,
	zones = {
	},
	subzones = {
	},
}
