-- AUTO-GENERATED by tools/voice/build-lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report
-- how long a sound file is; without them the Play button never resets itself.
--
-- A global rather than a private namespace: a data addon cannot reach into
-- ZoneLore's, which is how AI_VoiceOverData_Vanilla does the same job.

ZoneLoreAudioData = {
	version = 1,
	zones = {
		[1411] = { file = "1411/zone", len = 79.6 },
	},
	subzones = {
		[1411] = {
			["bladefist bay"] = { file = "1411/bladefist-bay", len = 49.6 },
			["bloodtalon shore"] = { file = "1411/bloodtalon-shore", len = 10.24 },
			["burning blade coven"] = { file = "1411/burning-blade-coven", len = 60.56 },
			["darkspear hold"] = { file = "1411/darkspear-hold", len = 15.76 },
			["darkspear isle"] = { file = "1411/darkspear-isle", len = 41.52 },
			["darkspear shore"] = { file = "1411/darkspear-shore", len = 19.44 },
			["darkspear strand"] = { file = "1411/darkspear-strand", len = 16.16 },
			["darkspear training grounds"] = { file = "1411/darkspear-training-grounds", len = 51.76 },
			["deadeye shore"] = { file = "1411/deadeye-shore", len = 34.24 },
			["den"] = { file = "1411/den", len = 34.16 },
			["dranoshar blockade"] = { file = "1411/dranoshar-blockade", len = 53.52 },
			["drygulch ravine"] = { file = "1411/drygulch-ravine", len = 67.52 },
			["dustwind cave"] = { file = "1411/dustwind-cave", len = 16.88 },
			["echo isles"] = { file = "1411/echo-isles", len = 22.8 },
			["hellscreams fist"] = { file = "1411/hellscreams-fist", len = 58.88 },
			["hidden path"] = { file = "1411/hidden-path", len = 28.72 },
			["jaggedswine farm"] = { file = "1411/jaggedswine-farm", len = 37.36 },
			["kolkar crag"] = { file = "1411/kolkar-crag", len = 50 },
			["northwatch foothold"] = { file = "1411/northwatch-foothold", len = 31.44 },
			["orgrimmar"] = { file = "1411/orgrimmar", len = 35.68 },
			["razor hill"] = { file = "1411/razor-hill", len = 53.2 },
			["razor hill barracks"] = { file = "1411/razor-hill-barracks", len = 18.8 },
			["razor hill outskirts"] = { file = "1411/razor-hill-outskirts", len = 11.2 },
			["razor hill watchtower"] = { file = "1411/razor-hill-watchtower", len = 36.16 },
			["razormane grounds"] = { file = "1411/razormane-grounds", len = 39.28 },
			["razorwind canyon"] = { file = "1411/razorwind-canyon", len = 56.24 },
			["rocktusk farm"] = { file = "1411/rocktusk-farm", len = 22.24 },
			["scuttle coast"] = { file = "1411/scuttle-coast", len = 43.84 },
			["senjin village"] = { file = "1411/senjin-village", len = 60.8 },
			["senjin village outskirts"] = { file = "1411/senjin-village-outskirts", len = 10.16 },
			["shrine of the dormant flame"] = { file = "1411/shrine-of-the-dormant-flame", len = 61.28 },
			["skull rock"] = { file = "1411/skull-rock", len = 21.68 },
			["southfury river"] = { file = "1411/southfury-river", len = 92.08 },
			["southfury watershed"] = { file = "1411/southfury-watershed", len = 61.12 },
			["spirit rock"] = { file = "1411/spirit-rock", len = 20.72 },
			["spitescale cavern"] = { file = "1411/spitescale-cavern", len = 7.84 },
			["spitescale cove"] = { file = "1411/spitescale-cove", len = 19.28 },
			["sunstrider"] = { file = "1411/sunstrider", len = 14.24 },
			["thunder ridge"] = { file = "1411/thunder-ridge", len = 7.04 },
			["tiragarde keep"] = { file = "1411/tiragarde-keep", len = 29.92 },
			["torkren farm"] = { file = "1411/torkren-farm", len = 36.48 },
			["valley of trials"] = { file = "1411/valley-of-trials", len = 80.4 },
			["zalazanes fall subzone"] = { file = "1411/zalazanes-fall-subzone", len = 34.48 },
		},
	},
}
