/**
 * Locating a line's audio in the store (audio/{quests,gossip}/*.mp3).
 *
 * `fileName` comes from the corpus, computed by Python. The only naming decision made on
 * this side is which subdirectory a line lives in, and it lives here alone - it is the
 * TypeScript twin of subfolder_from_line_id in tts_cli/naming.py. audio.test.ts pins the
 * two together by asserting every file in the store is addressed by some corpus line.
 */
import fs from "node:fs";
import path from "node:path";

import { loadCorpus, type CorpusLine } from "./corpus";
import { AUDIO_DIR } from "./paths";

export const SUBFOLDERS = ["quests", "gossip"] as const;

export function subfolder(line: Pick<CorpusLine, "source">): "quests" | "gossip" {
  return line.source === "gossip" ? "gossip" : "quests";
}

/** Store-relative path, e.g. "quests/5-accept.mp3". Also the /api/audio/ route path. */
export function audioRelPath(line: Pick<CorpusLine, "source" | "fileName">): string {
  return `${subfolder(line)}/${line.fileName}.mp3`;
}

/**
 * Every store path the corpus can address.
 *
 * A whitelist, and the reason the history playback route is traversal-proof by construction:
 * a path either names a file some corpus line owns or it does not exist, and no amount of
 * `../` produces a member of this set. Same reasoning as isVoiceSlot for voice names.
 *
 * Distinct from storeIndex, which is what is *on disk*. An archived take can be served for a
 * line whose current audio is missing, so membership here cannot depend on the store.
 */
const corpusFilesKey = Symbol.for("wow-voiceover.corpus-files");
type FilesHolder = { [corpusFilesKey]?: Set<string> };

export function corpusFiles(): Set<string> {
  const holder = globalThis as FilesHolder;
  if (!holder[corpusFilesKey]) {
    holder[corpusFilesKey] = new Set(loadCorpus().lines.map(audioRelPath));
  }
  return holder[corpusFilesKey]!;
}

export function readStoreIndex(audioDir: string = AUDIO_DIR): Set<string> {
  const found = new Set<string>();
  for (const sub of SUBFOLDERS) {
    const dir = path.join(audioDir, sub);
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir)) {
      if (name.endsWith(".mp3")) found.add(`${sub}/${name}`);
    }
  }
  return found;
}

/**
 * A cheap stand-in for "has the store changed": the mtime of each subdirectory.
 *
 * A directory's mtime moves when an entry is added or removed, which is exactly when
 * membership of the index changes - overwriting a file in place does not move it, and does
 * not need to, because the file was already in the set. Two stats, against the readdir of
 * ~9,500 entries they replace.
 */
function stamp(audioDir: string): string {
  return SUBFOLDERS.map((sub) => {
    try {
      return String(fs.statSync(path.join(audioDir, sub)).mtimeMs);
    } catch {
      // An absent subdirectory is a normal state (no audio imported yet) and a stable one.
      return "-";
    }
  }).join(",");
}

// One readdir of the two directories, memoised, instead of a stat per line: a search
// hitting 2,000 lines would otherwise make 2,000 syscalls.
const cacheKey = Symbol.for("wow-voiceover.store");
type CacheHolder = { [cacheKey]?: { set: Set<string>; stamp: string } };

/**
 * Every file in the store, re-read when the store changes underneath us.
 *
 * The memo used to be permanent, which was correct while nothing but rsync wrote here. Now
 * that a regeneration writes audio, it is not: pm2 runs two cluster workers, so a line
 * generated by one would read as "no audio" on the other until a reload. The stamp check is
 * what makes both workers agree, and it retires the `pm2 reload` that `make push` needed for
 * the same reason.
 */
export function storeIndex(audioDir: string = AUDIO_DIR): Set<string> {
  const holder = globalThis as CacheHolder;
  const current = stamp(audioDir);

  if (!holder[cacheKey] || holder[cacheKey].stamp !== current) {
    holder[cacheKey] = { set: readStoreIndex(audioDir), stamp: current };
  }
  return holder[cacheKey].set;
}

/**
 * Record a file this worker has just written, without waiting for the stamp to notice.
 *
 * Directory mtimes have filesystem-dependent granularity, so a write landing in the same
 * tick as the last refresh could otherwise stay invisible to the worker that made it - the
 * one case where being wrong is most visible, because someone is watching that line.
 */
export function noteStored(relPath: string): void {
  (globalThis as CacheHolder)[cacheKey]?.set.add(relPath);
}
