import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { loadCorpus } from "./corpus";
import { audioRelPath, corpusFiles, noteStored, storeIndex, subfolder } from "./audio";

describe("audio paths", () => {
  it("puts quest lines under quests/", () => {
    expect(audioRelPath({ source: "accept", fileName: "5-accept" })).toBe(
      "quests/5-accept.mp3",
    );
    expect(audioRelPath({ source: "complete", fileName: "123-complete" })).toBe(
      "quests/123-complete.mp3",
    );
  });

  it("puts gossip under gossip/", () => {
    expect(audioRelPath({ source: "gossip", fileName: "abc123" })).toBe(
      "gossip/abc123.mp3",
    );
  });

  it("keeps the gender prefix Python put in the filename", () => {
    // The prefix is part of fileName, never added here.
    expect(subfolder({ source: "gossip" })).toBe("gossip");
    expect(audioRelPath({ source: "gossip", fileName: "m-abc123" })).toBe(
      "gossip/m-abc123.mp3",
    );
  });
});

describe("store reconciliation", () => {
  const store = storeIndex();
  const addressed = new Set(loadCorpus().lines.map(audioRelPath));

  it("has an audio store to check", () => {
    // A fresh clone has no audio until `python cli-main.py import-audio` has run.
    if (store.size === 0) {
      console.warn("audio store is empty; run import-audio to exercise reconciliation");
    }
    expect(store.size).toBeGreaterThanOrEqual(0);
  });

  it("addresses every file in the store", () => {
    // The real assertion of this file: if the subfolder rule here ever diverged from
    // subfolder_from_line_id in tts_cli/naming.py, files would go unaddressed and the
    // explorer would report audio as missing while it sits on disk.
    const orphans = [...store].filter((rel) => !addressed.has(rel));
    expect(orphans).toEqual([]);
  });
});

/**
 * The memo used to be permanent, which was correct while nothing but rsync wrote here.
 * Regeneration writes audio, pm2 runs two cluster workers, and a line generated by one
 * worker would otherwise read as "no audio" on the other until a reload.
 */
describe("storeIndex freshness", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "store-index-"));
    fs.mkdirSync(path.join(dir, "quests"));
    fs.mkdirSync(path.join(dir, "gossip"));
    // The memo lives on globalThis, so a previous test's index would otherwise be reused.
    delete (globalThis as Record<symbol, unknown>)[Symbol.for("wow-voiceover.store")];
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
    delete (globalThis as Record<symbol, unknown>)[Symbol.for("wow-voiceover.store")];
  });

  it("picks up a file added after the first read, with no restart", () => {
    expect(storeIndex(dir).size).toBe(0);

    fs.writeFileSync(path.join(dir, "quests", "5-accept.mp3"), "audio");

    expect(storeIndex(dir).has("quests/5-accept.mp3")).toBe(true);
  });

  it("picks up a deletion too, so a removed file stops reading as present", () => {
    fs.writeFileSync(path.join(dir, "gossip", "abc.mp3"), "audio");
    expect(storeIndex(dir).has("gossip/abc.mp3")).toBe(true);

    fs.rmSync(path.join(dir, "gossip", "abc.mp3"));

    expect(storeIndex(dir).has("gossip/abc.mp3")).toBe(false);
  });

  it("reuses the memo while nothing changes", () => {
    fs.writeFileSync(path.join(dir, "quests", "5-accept.mp3"), "audio");
    expect(storeIndex(dir)).toBe(storeIndex(dir));
  });

  // Overwriting in place does not move a directory's mtime - and does not need to, because
  // the file was already in the set. This pins that the reasoning holds.
  it("keeps the same set when a file is overwritten rather than added", () => {
    const file = path.join(dir, "quests", "5-accept.mp3");
    fs.writeFileSync(file, "one");
    const first = storeIndex(dir);

    fs.writeFileSync(file, "two");

    expect(storeIndex(dir)).toBe(first);
    expect(storeIndex(dir).has("quests/5-accept.mp3")).toBe(true);
  });

  it("treats a store with no subdirectories as empty rather than throwing", () => {
    const bare = fs.mkdtempSync(path.join(os.tmpdir(), "store-bare-"));
    try {
      expect(storeIndex(bare).size).toBe(0);
    } finally {
      fs.rmSync(bare, { recursive: true, force: true });
    }
  });

  // noteStored covers the window the stamp cannot: a write landing in the same filesystem
  // mtime tick as the last refresh, on the very worker that made it.
  it("records a file the worker just wrote, without waiting for the stamp", () => {
    storeIndex(dir);
    noteStored("quests/99-accept.mp3");
    expect(storeIndex(dir).has("quests/99-accept.mp3")).toBe(true);
  });
});

/**
 * The whitelist the history playback route is built on. A path either names a file some
 * corpus line owns, or it does not exist - which is what makes `../` uninteresting rather
 * than something to sanitise away. Same reasoning as isVoiceSlot for voice names.
 */
describe("corpusFiles", () => {
  const files = corpusFiles();

  it("contains every path the explorer would link to", () => {
    for (const line of loadCorpus().lines.slice(0, 500)) {
      expect(files.has(audioRelPath(line))).toBe(true);
    }
  });

  it("holds one entry per distinct file, not per line", () => {
    // 14,315 generatable lines collapse to 11,081 files: a gossip file is named
    // md5(text + race + gender), so NPCs sharing a line share an mp3.
    expect(files.size).toBeLessThan(loadCorpus().lineCount);
    expect(files.size).toBeGreaterThan(10000);
  });

  it("rejects traversal and anything outside the two subfolders", () => {
    for (const bad of [
      "../etc/passwd",
      "quests/../../etc/passwd.mp3",
      "/etc/passwd",
      "sounds/5-accept.mp3",
      "quests/5-accept.wav",
      "quests/does-not-exist.mp3",
      "",
    ]) {
      expect(files.has(bad)).toBe(false);
    }
  });

  it("memoises", () => {
    expect(corpusFiles()).toBe(files);
  });
});
