#!/usr/bin/env node
//
// manifest.json -> addon/ZoneLoreAudio/Data/Sounds.lua
//
// Run after any generation. The addon resolves every clip through this table, so
// audio that is not in it is unreachable, and a row pointing at a file that is not
// on disk plays silence.

import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { ROOT } from "../lib/loredata.mjs";
import { loadManifest, SOUNDS_DIR } from "./store.mjs";

const OUT_PATH = join(ROOT, "addon/ZoneLoreAudio/Data/Sounds.lua");

function luaString(text) {
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

async function main() {
  const manifest = await loadManifest();

  const zones = new Map();      // mapID -> row
  const subzones = new Map();   // mapID -> Map(key -> row)
  let missingFiles = 0;

  for (const [id, record] of Object.entries(manifest)) {
    if (!existsSync(join(SOUNDS_DIR, `${record.file}.mp3`))) {
      console.warn(`warning: ${id} is in the manifest but ${record.file}.mp3 is not on disk`);
      missingFiles++;
      continue;
    }

    const [kind, mapIDText, ...rest] = id.split(":");
    const mapID = Number(mapIDText);
    const row = { file: record.file, len: record.durationSec };

    if (kind === "z") {
      zones.set(mapID, row);
    } else if (kind === "s") {
      // Rejoin: a canonical key never contains a colon, but splitting on one and
      // taking [2] would quietly truncate it if that ever stopped being true.
      const key = rest.join(":");
      if (!subzones.has(mapID)) subzones.set(mapID, new Map());
      subzones.get(mapID).set(key, row);
    } else {
      throw new Error(`unknown lineId kind in ${id}`);
    }
  }

  const lines = [
    "-- AUTO-GENERATED by tools/voice/build-lookup.mjs. Do not edit by hand.",
    "--",
    "-- Durations are recorded at generation time because the client cannot report",
    "-- how long a sound file is; without them the Play button never resets itself.",
    "--",
    "-- A global rather than a private namespace: a data addon cannot reach into",
    "-- ZoneLore's, which is how AI_VoiceOverData_Vanilla does the same job.",
    "",
    "ZoneLoreAudioData = {",
    "\tversion = 1,",
    "\tzones = {",
  ];

  for (const mapID of [...zones.keys()].sort((a, b) => a - b)) {
    const row = zones.get(mapID);
    lines.push(`\t\t[${mapID}] = { file = ${luaString(row.file)}, len = ${row.len} },`);
  }

  lines.push("\t},", "\tsubzones = {");

  for (const mapID of [...subzones.keys()].sort((a, b) => a - b)) {
    lines.push(`\t\t[${mapID}] = {`);
    const table = subzones.get(mapID);
    for (const key of [...table.keys()].sort()) {
      const row = table.get(key);
      lines.push(`\t\t\t[${luaString(key)}] = { file = ${luaString(row.file)}, len = ${row.len} },`);
    }
    lines.push("\t\t},");
  }

  lines.push("\t},", "}", "");

  await mkdir(join(ROOT, "addon/ZoneLoreAudio/Data"), { recursive: true });
  await writeFile(OUT_PATH, lines.join("\n"));

  const subzoneCount = [...subzones.values()].reduce((n, t) => n + t.size, 0);
  console.log(`wrote ${OUT_PATH}`);
  console.log(`  ${zones.size} zones, ${subzoneCount} subzones across ${subzones.size} zones`);
  if (missingFiles) {
    console.log(`  ${missingFiles} manifest entries skipped: no file on disk`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(`error: ${err.message}`);
  process.exit(1);
});
