-- AUTO-GENERATED by pipelines/books/tools/build-lookup.mjs. Do not edit by hand.
--
-- Durations are recorded at generation time because the client cannot report how long
-- a sound file is; without them the Play button never resets itself.
--
-- A page with no clip is simply absent. There is no stand-in: substituting unrelated
-- audio is worse than silence, because silence is honest about what is missing.
--
-- Globals rather than a private namespace: a data addon cannot reach into SpokenBooks's.

local ADDON_NAME = ...

local pack = {
	version = 1,
	addon = ADDON_NAME,
	quality = "high",
	bitrate = 128,
	language = "enUS",
	pages = {
		[45] = { file = "45", len = 13.2 },
	},
}

SpokenBooksAudioPacks = SpokenBooksAudioPacks or {}
SpokenBooksAudioPacks[ADDON_NAME] = pack
