// The two addon data files, emitted from records.
//
// Lifted verbatim out of tools/scrape.mjs and tools/scrape-subzones.mjs, which used to
// own one emitter each. They now hand their entries to the lore store instead, and the
// export reads them back out of Postgres, so the code that decides what the Lua looks
// like has to be reachable from both paths. Byte-for-byte identical output is the
// property the migration is checked against: seed the table from the committed files,
// export, and see no diff.
//
// tools/lib/loredata.mjs is the reader for exactly this format. The two move together.

import { luaString } from "../lib/wiki.mjs";

/**
 * addon/ZoneLore/Data/Zones.lua.
 *
 * @param entries {name, short, full, source, mapID}[] -- any order; sorted here, because
 *   a data file whose order depends on how the rows came back is a diff on every export.
 */
export function emitZones(entries) {
  const lines = [
    "-- AUTO-GENERATED by tools/lore/export.mjs. Do not edit by hand; your changes will",
    "-- be overwritten. Edit the lore through the explorer, or adjust tools/seed/zones.json",
    "-- and re-scrape.",
    "--",
    "-- Lore text from warcraft.wiki.gg, licensed CC BY-SA 4.0, except where an entry has",
    "-- no source: that prose was written for this project.",
    "-- Page intros only, with post-vanilla sentences filtered out for Classic Era.",
    "",
    "local _, ZoneLore = ...",
    "",
    "ZoneLore.Zones = {",
  ];

  for (const e of [...entries].sort((a, b) => a.mapID - b.mapID)) {
    lines.push(`\t[${e.mapID}] = {`);
    lines.push(`\t\tname = ${luaString(e.name)},`);
    lines.push(`\t\tshort = ${luaString(e.short)},`);
    lines.push(`\t\tfull = ${luaString(e.full)},`);
    lines.push(`\t\tsource = ${luaString(e.source ?? "")},`);
    lines.push("\t},");
  }

  lines.push("}", "");
  return lines.join("\n");
}

/**
 * addon/ZoneLore/Data/Subzones.lua.
 *
 * @param entries {mapID, key, name, short, full, source}[]
 * @param zoneNames Map<mapID, string> for the per-zone comment. A subzone row carries
 *   only its parent's uiMapID, and "-- Durotar: 43 subzones" is the only thing making
 *   a 1300-entry file skimmable.
 */
export function emitSubzones(entries, zoneNames) {
  const lines = [
    "-- AUTO-GENERATED by tools/lore/export.mjs. Do not edit by hand.",
    "--",
    "-- Lore text from warcraft.wiki.gg, licensed CC BY-SA 4.0, except where an entry has",
    "-- no source: that prose was written for this project.",
    "--",
    "-- Keyed by parent uiMapID, then by NORMALISED subzone name: lower case, a",
    '-- leading "the " removed, apostrophes dropped, punctuation collapsed to',
    '-- single spaces. The client reports "The Bulwark" where the wiki titles the',
    '-- page "Bulwark", so both sides are reduced to the same key at lookup time',
    "-- via ZoneLore:NormaliseAreaKey.",
    "",
    "local _, ZoneLore = ...",
    "",
    "ZoneLore.Subzones = {",
  ];

  const byZone = new Map();
  for (const entry of entries) {
    if (!byZone.has(entry.mapID)) byZone.set(entry.mapID, []);
    byZone.get(entry.mapID).push(entry);
  }

  for (const mapID of [...byZone.keys()].sort((a, b) => a - b)) {
    // Default code-unit order, not localeCompare: this reproduces what the scraper's
    // `[...entries.keys()].sort()` produced, and the keys are already normalised to
    // lower case so the two agree in practice anyway.
    const zoneEntries = [...byZone.get(mapID)].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
    lines.push(`\t-- ${zoneNames.get(mapID) ?? mapID}: ${zoneEntries.length} subzones`);
    lines.push(`\t[${mapID}] = {`);
    for (const e of zoneEntries) {
      lines.push(`\t\t[${luaString(e.key)}] = {`);
      lines.push(`\t\t\tname = ${luaString(e.name)},`);
      lines.push(`\t\t\tshort = ${luaString(e.short)},`);
      lines.push(`\t\t\tfull = ${luaString(e.full)},`);
      lines.push(`\t\t\tsource = ${luaString(e.source ?? "")},`);
      lines.push("\t\t},");
    }
    lines.push("\t},");
  }

  lines.push("}", "");
  return lines.join("\n");
}
