// take -> addons/SpokenBooksAudio/Data/Sounds.lua.
//
// The sound pack's own table: which clip narrates which page, and how long it runs.
// Durations are recorded at generation time because the client cannot report the length of
// a sound file, and without them the player's Play button never resets itself.
//
// Separate from the corpus export on purpose. This changes when a clip is cut; Books.lua
// changes when a page's text does. One file rewritten for the other's reasons is a diff
// nobody can read.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import pg from "pg";

const OUT = new URL("../../../addons/SpokenBooksAudio/Data/Sounds.lua", import.meta.url).pathname;
const LANG = "enUS";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is not set -- the takes live in Postgres");

const pool = new pg.Pool({ connectionString: url });

try {
  // Joined to the corpus rather than trusting the take's lineId: a take for a page that is
  // no longer in the corpus has nothing to narrate, and an entry for it would be a row the
  // addon can never reach.
  const { rows } = await pool.query(
    `select b."pageId", t."file", t."durationSec"
       from "take" t
       join "book_line" b on b."lineId" = t."lineId" and b."lang" = t."lang" and b."isCurrent"
      where t."source" = 'books' and t."isCurrent" and t."lang" = $1
      order by b."pageId"`,
    [LANG],
  );

  const lines = [
    `-- AUTO-GENERATED by pipelines/books/tools/build-lookup.mjs. Do not edit by hand.`,
    `--`,
    `-- Durations are recorded at generation time because the client cannot report how long`,
    `-- a sound file is; without them the Play button never resets itself.`,
    `--`,
    `-- A page with no clip is simply absent. There is no stand-in: substituting unrelated`,
    `-- audio is worse than silence, because silence is honest about what is missing.`,
    `--`,
    `-- Globals rather than a private namespace: a data addon cannot reach into SpokenBooks's.`,
    ``,
    `local ADDON_NAME = ...`,
    ``,
    `local pack = {`,
    `\tversion = 1,`,
    `\taddon = ADDON_NAME,`,
    `\tquality = "high",`,
    `\tbitrate = 128,`,
    `\tlanguage = "${LANG}",`,
    `\tpages = {`,
  ];

  for (const row of rows) {
    // Null only for a take imported from a store this app did not cut. Written as 0 so the
    // addon can tell "unknown" from "short" and fall back to its own timer.
    const len = row.durationSec === null ? 0 : row.durationSec;
    lines.push(`\t\t[${row.pageId}] = { file = "${row.file}", len = ${len} },`);
  }

  lines.push(
    `\t},`,
    `}`,
    ``,
    `SpokenBooksAudioPacks = SpokenBooksAudioPacks or {}`,
    `SpokenBooksAudioPacks[ADDON_NAME] = pack`,
    ``,
  );

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, lines.join("\n"));

  console.log(`${rows.length} clips -> ${OUT}`);
} finally {
  await pool.end();
}
