-- AUTO-GENERATED by tools/locale/build-aliases.mjs. Do not edit by hand.
--
-- Area names as a itIT client reports them, mapped to the English keys the
-- corpus is stored under. Built by joining AreaTable's localized and English
-- strings on their shared ID, from client build 1.15.9.69109.
--
-- Keyed by the raw client name: ZoneLore:NormaliseAreaKey reduces a name to
-- [a-z0-9 ], which erases a Cyrillic or Chinese name entirely.

local _, ZoneLore = ...

if not ZoneLore:ShouldLoadAliases("itIT") then
	return
end

local aliases = {
}

ZoneLore:RegisterAliases("itIT", aliases)
