setfenv(1, SpokenEnv)

-- Interface strings. English only for now; a locale file per language can overlay this
-- table the way the zones addon's Locale/ files do, once there is a second language.
L = {
    PLAY = "Play",
    PAUSE = "Pause",
    PAUSE_TOOLTIP = "Pause stops the clip; play starts it again from the beginning. The game cannot resume a sound part-way through.",
    STOP = "Stop",
    SETTINGS = "Settings",
    PLAY_PAUSE = "Play/Pause",
    QUEUE_TITLE = "Up next",
    -- The settings heading for the window above, which "Up next" -- the window's own
    -- title, on its tooltip -- did not describe.
    OPT_WINDOW_TITLE = "Player window",
    QUEUE_DRAG_HINT = "Drag to move. The position can be locked in settings.",
    QUEUE_REMOVE_TOOLTIP = "Click to take this out of the queue.",
    MENU_LEFT = "|cff66bbffLeft-click|r open the menu",
    MENU_RIGHT = "|cff66bbffRight-click|r open settings",
    MENU_MIDDLE = "|cff66bbffMiddle-click|r play/pause",
    OPT_LOCK_FRAME = "Lock the player",
    OPT_LOCK_FRAME_TIP = "Prevent the player from being moved or resized.",
    OPT_HIDE_PORTRAIT = "Hide the portrait",
    OPT_HIDE_PORTRAIT_TIP = "Show the queue without the speaker's portrait. Useful alongside addons that replace the dialog window.",
    OPT_HIDE_FRAME = "Hide the player entirely",
    OPT_HIDE_FRAME_TIP = "Play everything without ever showing the window.",
    OPT_SCALE = "Player scale",
    OPT_RESET = "Reset position",
    OPT_AUDIO_TITLE = "Audio",
    OPT_CHANNEL = "Sound channel: %s",
    OPT_CHANNEL_TIP = "Which of the game's sound channels every Spoken addon speaks on. Each follows its own volume slider in the game's sound options.",
    OPT_MUTE_DIALOGUE = "Silence the game's own dialogue while speaking",
    OPT_MUTE_DIALOGUE_TIP = "Mute the Dialog channel while a line is being read, so an NPC's own voice does not talk over it. Restored when the queue empties.",
    OPT_MUTE_DIALOGUE_TIP_VANILLA = "Cut off an NPC's greeting voiceline when a line starts being read.",
    OPT_MUSIC_CHANNEL = "Play through the music channel",
    OPT_MUSIC_CHANNEL_TIP = "This client cannot stop a sound once it has started, so speech is routed through the music channel, which can be stopped. Turn this off and a line cannot be paused or skipped once it starts.",
    OPT_MUSIC_VOLUME = "Speech volume",
    OPT_MUSIC_FADE = "Fade the music out over",
    OPT_HD_MODELS = "HD model patch installed",
    OPT_HD_MODELS_TIP = "Use the animation timings of the high-definition character models, if you have patched them in. Portraits will mouth their lines out of step otherwise.",
    OPT_MINIMAP_TITLE = "Minimap",
    OPT_ADDONS_TITLE = "Spoken addons",
    OPT_MINIMAP_SHOW = "Show the minimap button",
    OPT_MINIMAP_LOCK = "Lock the minimap button",
    OPT_NO_SETTINGS_API = "open Game Menu -> Options -> AddOns -> Spoken Player, or type /spoken options",
}
