import { describe, expect, it, vi } from "vitest";

import { buildPayload, textToSpeech } from "./tts";

const SETTINGS = {
  stability: 0.5,
  similarity_boost: 0.75,
  style: 0,
  use_speaker_boost: true,
} as const;

const REQUEST = {
  voiceId: "voice-abc",
  text: "Hmm. The mines are not safe.",
  modelId: "eleven_multilingual_v2",
  voiceSettings: { ...SETTINGS },
  seed: 1163733943,
};

function audioResponse(body = "ID3fake-mp3-bytes", cost = "17"): Response {
  return new Response(body, {
    status: 200,
    headers: { "content-type": "audio/mpeg", "character-cost": cost },
  });
}

function stub(response: Response | Promise<Response>) {
  return vi.fn(async () => response) as unknown as typeof globalThis.fetch;
}

const OPTIONS = { apiKey: "test-key", baseUrl: "https://stub.invalid" };

/**
 * The payload has to match build_payload in tts_cli/synthesize.py exactly. The addon
 * resolves a sound by filename and cannot tell which side produced it, so a line generated
 * here and a line generated by the CLI must be the same kind of thing.
 */
describe("buildPayload", () => {
  it("sends what the Python generator sends", () => {
    expect(buildPayload(REQUEST)).toEqual({
      text: "Hmm. The mines are not safe.",
      model_id: "eleven_multilingual_v2",
      voice_settings: SETTINGS,
      seed: 1163733943,
    });
  });

  /**
   * The one place the two generators no longer match. synthesize.py sends no dictionary at
   * all, so a line it produces and a line produced here can differ in pronunciation with
   * otherwise identical settings - which is exactly why the locator is recorded per take.
   */
  it("sends no dictionary when there is none, matching the Python payload", () => {
    expect(buildPayload({ ...REQUEST, dictionary: null })).not.toHaveProperty(
      "pronunciation_dictionary_locators",
    );
    expect(buildPayload(REQUEST)).not.toHaveProperty("pronunciation_dictionary_locators");
  });

  // The version is not optional. Naming the dictionary alone would let a later upload change
  // how an already-recorded take would sound, which is what dictionaryVersion exists to pin.
  it("pins the dictionary to a version when one is in force", () => {
    const payload = buildPayload({
      ...REQUEST,
      dictionary: { dictionaryId: "dict-abc", versionId: "ver-1" },
    });
    expect(payload.pronunciation_dictionary_locators).toEqual([
      { pronunciation_dictionary_id: "dict-abc", version_id: "ver-1" },
    ]);
  });

  // Python omits the key entirely when the strategy is "none"; sending null would be a value
  // ElevenLabs has to interpret rather than a field it never sees.
  it("omits the seed rather than sending null", () => {
    expect(buildPayload({ ...REQUEST, seed: null })).not.toHaveProperty("seed");
  });

  it("does not set an output format, so both sides take the API's default", () => {
    expect(buildPayload(REQUEST)).not.toHaveProperty("output_format");
  });
});

describe("textToSpeech", () => {
  it("posts to the voice's endpoint with the key", async () => {
    const fetchImpl = stub(audioResponse());
    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });

    expect(result).toEqual({ ok: true, audio: Buffer.from("ID3fake-mp3-bytes"), credits: 17 });

    const [url, init] = (fetchImpl as unknown as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe("https://stub.invalid/v1/text-to-speech/voice-abc");
    expect(init.method).toBe("POST");
    expect(init.headers["xi-api-key"]).toBe("test-key");
    expect(JSON.parse(init.body)).toEqual(buildPayload(REQUEST));
  });

  it("reports running out of credits as a stopping condition", async () => {
    const fetchImpl = stub(
      new Response(JSON.stringify({ detail: { status: "quota_exceeded", message: "no credits" } }), {
        status: 401,
      }),
    );

    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.failure.kind).toBe("quota");
    expect(result.failure.fatal).toBe(true);
    expect(result.failure.message).toContain("no credits");
  });

  /**
   * The check synthesize.py makes, and it earns its place: an error served with a 200 would
   * otherwise be written into the store as an mp3 and play as silence in the game - a
   * failure nothing would notice until someone talked to that NPC.
   */
  it("refuses a 200 that is not audio", async () => {
    const fetchImpl = stub(
      new Response(JSON.stringify({ detail: "something went wrong" }), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
    );

    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.failure.message).toContain("application/json");
    expect(result.failure.message).toContain("rather than audio");
  });

  it("refuses an empty 200 rather than storing a zero-byte mp3", async () => {
    const fetchImpl = stub(
      new Response("", { status: 200, headers: { "content-type": "audio/mpeg" } }),
    );

    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.failure.message).toContain("empty");
  });

  it("accepts any audio content type, not only audio/mpeg", async () => {
    const fetchImpl = stub(
      new Response("bytes", { status: 200, headers: { "content-type": "audio/mp3" } }),
    );
    expect((await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl })).ok).toBe(true);
  });

  // A dropped connection says nothing about the next line, so it must not stop a batch.
  it("survives a transport failure without stopping the batch", async () => {
    const fetchImpl = vi.fn(async () => {
      throw new Error("ECONNRESET");
    }) as unknown as typeof globalThis.fetch;

    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.failure.kind).toBe("upstream");
    expect(result.failure.fatal).toBe(false);
    expect(result.failure.message).toContain("ECONNRESET");
  });

  it("refuses to call out at all with no key", async () => {
    const fetchImpl = vi.fn() as unknown as typeof globalThis.fetch;
    const result = await textToSpeech(REQUEST, { apiKey: "", baseUrl: "x", fetchImpl });

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.failure.kind).toBe("auth");
    expect(fetchImpl).not.toHaveBeenCalled();
  });
});

/**
 * ElevenLabs does not bill the characters you send. It bills round(characters * rate), and
 * the rate belongs to the plan: measured at 0.55 on the account this was built against, so
 * a 310-character line cost 170. The header is the only way to know the real figure without
 * guessing at someone's plan, and it agreed with the usage-stats delta on every model and
 * length tried.
 */
describe("what a request actually cost", () => {
  it("reports the cost ElevenLabs charged, not the length of the text", async () => {
    const fetchImpl = stub(audioResponse("ID3bytes", "55"));
    const result = await textToSpeech({ ...REQUEST, text: "A".repeat(100) }, { ...OPTIONS, fetchImpl });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.credits).toBe(55);
  });

  // Reporting a number that was not charged is worse than reporting none: the whole reason
  // this is read rather than computed is that the rate cannot be derived from the request.
  it("reports nothing rather than guessing when the header is absent", async () => {
    const fetchImpl = stub(
      new Response("ID3bytes", { status: 200, headers: { "content-type": "audio/mpeg" } }),
    );
    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.credits).toBeNull();
  });

  it("ignores a header that is not a usable number", async () => {
    for (const cost of ["", "unknown", "-5", "NaN"]) {
      const fetchImpl = stub(audioResponse("ID3bytes", cost));
      const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });
      expect(result.ok && result.credits).toBeFalsy();
    }
  });

  it("reads a zero cost as zero, not as absent", async () => {
    const fetchImpl = stub(audioResponse("ID3bytes", "0"));
    const result = await textToSpeech(REQUEST, { ...OPTIONS, fetchImpl });
    expect(result.ok && result.credits).toBe(0);
  });
});
